# Generated by Django 4.0.6 on 2022-08-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
